cache_ttl_seconds: 3600
threads: 4
faiss_enabled: false

bitbucket:
  project_key: "STARSYSONE"
  repos:
    - "policycenter"
    - "claimcenter"
    - "billingcenter"
    - "contactmanager"
  branch_defaults:
    - "develop"
  branch_pattern: "release/r-*"
jira:
  jql_default: ""
